In [1]:
import numpy as np

In [2]:
lst=[1,2,3]

In [3]:
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3])

In [5]:
matrix=[[1,3,4],[1,2,3],[1,1,1]]

In [6]:
np.array(matrix)

array([[1, 3, 4],
       [1, 2, 3],
       [1, 1, 1]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#linspace gives5 evenly spaced points from 1 to 10 while arange gives arange(1,10,2) gives points from 1-9 and each with a step size of two

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

for arrays of random nums

In [25]:
np.random.rand()

0.7978096766489171

In [27]:
np.random.rand(4)
#gives random nums from 0 to 1

array([0.32607945, 0.74382367, 0.21853802, 0.36166235])

In [28]:
np.random.rand(8)

array([0.79078022, 0.89072445, 0.5048297 , 0.687605  , 0.85742498,
       0.88742142, 0.70861405, 0.34115237])

In [30]:
np.random.rand(3,3)

array([[0.5291133 , 0.2820862 , 0.80351041],
       [0.98499005, 0.21623068, 0.44407761],
       [0.26405581, 0.80065942, 0.55174577]])

In [31]:
#to get random nums from gaussian/standard distribution the use 

In [32]:
np.random.randn(2)

array([-1.90416132,  1.34841274])

In [33]:
np.random.randn(2,2)

array([[-0.05801962, -0.15155648],
       [-0.86817721, -0.19868674]])

In [42]:
np.random.randint(1,100,4)

array([90, 21, 84, 47])

In [34]:
np.random.randint(1,100)

51

In [43]:
randarr=np.random.randint(1,100,4)

In [44]:
randarr

array([81, 25, 94, 36])

In [37]:
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [38]:
arr=np.arange(1,100,4)

In [39]:
arr.reshape(5,5)

array([[ 1,  5,  9, 13, 17],
       [21, 25, 29, 33, 37],
       [41, 45, 49, 53, 57],
       [61, 65, 69, 73, 77],
       [81, 85, 89, 93, 97]])

In [45]:
randarr.max()

94

In [46]:
randarr.min()

25

In [47]:
randarr.argmax()

2

In [48]:
randarr.argmin()

1

In [50]:
randarr.shape

(4,)

In [51]:
arr.shape

(25,)

In [52]:
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [55]:
arr.dtype


dtype('int32')

In [56]:
arr1=np.arange(0,11)

In [57]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr1[5]

5

In [62]:
arr1[1:5]

array([1, 2, 3, 4])

In [63]:
arr1[1:5]=100

In [64]:
arr1

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
#here the original array is being changed

In [66]:
arr2=arr1.copy()

In [68]:
arr2[:]=1

In [69]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [70]:
arr1

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#2D array

In [72]:
arr2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [74]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr2d[0][0]

5

In [76]:
arr2d[0]

array([ 5, 10, 15])

In [78]:
arr2d[2][1]

40

In [79]:
arr2d[2,1]

40

In [80]:
arr2d[:2][1:]

array([[20, 25, 30]])

In [81]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [82]:
arr2d>6

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [83]:
arr2d[arr2d>6]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [84]:
arr4=np.arange(0,10)

In [85]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr4-arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr4*arr4

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
arr4+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [89]:
arr4/arr4

<ipython-input-89-b03270b0b3a8>:1: RuntimeWarning: invalid value encountered in true_divide
  arr4/arr4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
arr**2

array([   1,   25,   81,  169,  289,  441,  625,  841, 1089, 1369, 1681,
       2025, 2401, 2809, 3249, 3721, 4225, 4761, 5329, 5929, 6561, 7225,
       7921, 8649, 9409], dtype=int32)

In [92]:
np.sqrt(arr4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.exp(arr4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [94]:
np.max(arr4)

9

In [95]:
np.sin(arr4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])